### PR TITLE
Add prices to list of fund tokens

### PR DESCRIPTION
**Pull request by mrruby**
- current token price in the list of tokens in fund; return 1.00 when no price (stable coin case)

### CODE REVIEW

**Comment by raashidjunaid1** [comment]
I don't see where the prices are being used in the SDK itself, whats the use-case here?

**Comment by mrruby** [comment]
Sorry, it's just the improvement for the SDK so you will be able to show the asset value as % of the whole fund value. 
It would be great to add it to the response because prices are already fetched by the SDK so you don't need to do this in the client site

**Comment by raashidjunaid1** [comment]
Sure but `mapTokens(..)` is only getting used in `getPerformance()` and hence getting lost as it only exports `updatedPerformance, currentAum`

**Comment by raashidjunaid1** [comment]
The point of this pr is to expose prices as they are already fetched by the SDK, but that is not being achieved. `mapTokens()` is only being used by `getPerformance()` which only returns `updatedPerformance, currentAum` and not the prices.

**Comment by mrruby** [comment]
I'm using ```getInvestmentsByInvestorAddress``` function from SDK in my dapp and this PR expose tokens prices in this function response

**Comment by raashidjunaid1** [comment]
not sure if you have seen my above message ^^

**Comment by raashidjunaid1** [comment]
not sure if you have seen my above message ^^

**Comment by mrruby** [comment]
Understood

**Pull request closed without merging**
